version: '3'
services:
  db:
    image: postgres:11
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test_db
  application:
    build:
      context: ../application
      dockerfile: ../docker/Dockerfile
    volumes:
      - ../application:/code
    ports:
      - "3000:3000"
    depends_on:
      - db